service: mhfa

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    SLACK_HOOK_URL: ${env:SLACK_HOOK_URL}

functions:
  mhfa-slack-handler:
    handler: src/slack.handler
    events:
      - http:
          method: post
          path: /slack/events
